language: go

go:
  - 1.7

install:
  - export PATH=$GOPATH/bin:./_output/tools/etcd/bin:$PATH
  - git fetch origin 'refs/tags/*:refs/tags/*'
  - make install-travis

script:
  - make verify-commits

notifications:
  irc: "chat.freenode.net#openshift-dev"

sudo: false
